services:

  # ------------------------------------
  # 1. DATABASE
  # ------------------------------------
  db:
    container_name: domas_db
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: domas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - domas_net

  # ------------------------------------
  # 2. SERVER
  # ------------------------------------
  server:
    container_name: domas_server
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/domas
      - SESSION_SECRET=fee30131828e46e3a2dc70ede1d65251ab342a4d3781c52fdd508191a0f28ea5
      - APP_USER=domas_app
      - APP_USER_PASSWORD=domas_app_pass
    networks:
      - domas_net
    depends_on:
      - db

  # ------------------------------------
  # 3. STUDENT CLIENT
  # ------------------------------------
  client-student:
    container_name: domas_student
    build:
      context: .
      dockerfile: apps/client-student/Dockerfile
      args:
        VITE_API_URL: "http://34.7.213.46:3000"
    restart: always
    ports:
      - "8081:80"
    networks:
      - domas_net
    depends_on:
      - server

  # ------------------------------------
  # 4. MAIN CLIENT (ADMIN)
  # ------------------------------------
  client:
    container_name: domas_client
    build:
      context: .
      dockerfile: apps/client/Dockerfile
      args:
        # CHANGED: Use relative path to hit the Nginx proxy
        VITE_API_URL: "/api"
    restart: always
    ports:
      - "80:80"
    networks:
      - domas_net
    depends_on:
      - server

networks:
  domas_net:
    driver: bridge

volumes:
  postgres_data: