export interface CountrySeed {
  code: string;
  nameEn: string;
  nameTr: string;
}

// Seed data only - the `countries` table is the source of truth at runtime
// and is admin-editable. This list is used once to populate an empty table
// (see apps/server/scripts/init-production.ts).
export const COUNTRY_SEEDS: CountrySeed[] = [
  { code: "AF", nameEn: "Afghanistan", nameTr: "Afganistan" },
  { code: "AX", nameEn: "Åland Islands", nameTr: "Åland Adaları" },
  { code: "AL", nameEn: "Albania", nameTr: "Arnavutluk" },
  { code: "DZ", nameEn: "Algeria", nameTr: "Cezayir" },
  { code: "AS", nameEn: "American Samoa", nameTr: "Amerikan Samoası" },
  { code: "AD", nameEn: "Andorra", nameTr: "Andorra" },
  { code: "AO", nameEn: "Angola", nameTr: "Angola" },
  { code: "AI", nameEn: "Anguilla", nameTr: "Anguilla" },
  { code: "AQ", nameEn: "Antarctica", nameTr: "Antarktika" },
  { code: "AG", nameEn: "Antigua and Barbuda", nameTr: "Antigua ve Barbuda" },
  { code: "AR", nameEn: "Argentina", nameTr: "Arjantin" },
  { code: "AM", nameEn: "Armenia", nameTr: "Ermenistan" },
  { code: "AW", nameEn: "Aruba", nameTr: "Aruba" },
  { code: "AU", nameEn: "Australia", nameTr: "Avustralya" },
  { code: "AT", nameEn: "Austria", nameTr: "Avusturya" },
  { code: "AZ", nameEn: "Azerbaijan", nameTr: "Azerbaycan" },
  { code: "BS", nameEn: "Bahamas", nameTr: "Bahamalar" },
  { code: "BH", nameEn: "Bahrain", nameTr: "Bahreyn" },
  { code: "BD", nameEn: "Bangladesh", nameTr: "Bangladeş" },
  { code: "BB", nameEn: "Barbados", nameTr: "Barbados" },
  { code: "BY", nameEn: "Belarus", nameTr: "Belarus" },
  { code: "BE", nameEn: "Belgium", nameTr: "Belçika" },
  { code: "BZ", nameEn: "Belize", nameTr: "Belize" },
  { code: "BJ", nameEn: "Benin", nameTr: "Benin" },
  { code: "BM", nameEn: "Bermuda", nameTr: "Bermuda" },
  { code: "BT", nameEn: "Bhutan", nameTr: "Bhutan" },
  { code: "BO", nameEn: "Bolivia", nameTr: "Bolivya" },
  {
    code: "BQ",
    nameEn: "Bonaire, Sint Eustatius and Saba",
    nameTr: "Bonaire, Sint Eustatius ve Saba",
  },
  { code: "BA", nameEn: "Bosnia and Herzegovina", nameTr: "Bosna Hersek" },
  { code: "BW", nameEn: "Botswana", nameTr: "Botsvana" },
  { code: "BV", nameEn: "Bouvet Island", nameTr: "Bouvet Adası" },
  { code: "BR", nameEn: "Brazil", nameTr: "Brezilya" },
  {
    code: "IO",
    nameEn: "British Indian Ocean Territory",
    nameTr: "Britanya Hint Okyanusu Toprakları",
  },
  { code: "BN", nameEn: "Brunei Darussalam", nameTr: "Brunei" },
  { code: "BG", nameEn: "Bulgaria", nameTr: "Bulgaristan" },
  { code: "BF", nameEn: "Burkina Faso", nameTr: "Burkina Faso" },
  { code: "BI", nameEn: "Burundi", nameTr: "Burundi" },
  { code: "CV", nameEn: "Cabo Verde", nameTr: "Cabo Verde" },
  { code: "KH", nameEn: "Cambodia", nameTr: "Kamboçya" },
  { code: "CM", nameEn: "Cameroon", nameTr: "Kamerun" },
  { code: "CA", nameEn: "Canada", nameTr: "Kanada" },
  { code: "KY", nameEn: "Cayman Islands", nameTr: "Cayman Adaları" },
  {
    code: "CF",
    nameEn: "Central African Republic",
    nameTr: "Orta Afrika Cumhuriyeti",
  },
  { code: "TD", nameEn: "Chad", nameTr: "Çad" },
  { code: "CL", nameEn: "Chile", nameTr: "Şili" },
  { code: "CN", nameEn: "China", nameTr: "Çin" },
  { code: "CX", nameEn: "Christmas Island", nameTr: "Noel Adası" },
  {
    code: "CC",
    nameEn: "Cocos (Keeling) Islands",
    nameTr: "Cocos (Keeling) Adaları",
  },
  { code: "CO", nameEn: "Colombia", nameTr: "Kolombiya" },
  { code: "KM", nameEn: "Comoros", nameTr: "Komorlar" },
  { code: "CG", nameEn: "Congo", nameTr: "Kongo" },
  {
    code: "CD",
    nameEn: "Congo, The Democratic Republic of the",
    nameTr: "Kongo Demokratik Cumhuriyeti",
  },
  { code: "CK", nameEn: "Cook Islands", nameTr: "Cook Adaları" },
  { code: "CR", nameEn: "Costa Rica", nameTr: "Kosta Rika" },
  { code: "CI", nameEn: "Cote D'Ivoire", nameTr: "Fildişi Sahili" },
  { code: "HR", nameEn: "Croatia", nameTr: "Hırvatistan" },
  { code: "CU", nameEn: "Cuba", nameTr: "Küba" },
  { code: "CW", nameEn: "Curaçao", nameTr: "Curaçao" },
  { code: "CY", nameEn: "Cyprus", nameTr: "Kıbrıs" },
  { code: "CZ", nameEn: "Czechia", nameTr: "Çekya" },
  { code: "DK", nameEn: "Denmark", nameTr: "Danimarka" },
  { code: "DJ", nameEn: "Djibouti", nameTr: "Cibuti" },
  { code: "DM", nameEn: "Dominica", nameTr: "Dominika" },
  { code: "DO", nameEn: "Dominican Republic", nameTr: "Dominik Cumhuriyeti" },
  { code: "EC", nameEn: "Ecuador", nameTr: "Ekvador" },
  { code: "EG", nameEn: "Egypt", nameTr: "Mısır" },
  { code: "SV", nameEn: "El Salvador", nameTr: "El Salvador" },
  { code: "GQ", nameEn: "Equatorial Guinea", nameTr: "Ekvator Ginesi" },
  { code: "ER", nameEn: "Eritrea", nameTr: "Eritre" },
  { code: "EE", nameEn: "Estonia", nameTr: "Estonya" },
  { code: "ET", nameEn: "Ethiopia", nameTr: "Etiyopya" },
  {
    code: "FK",
    nameEn: "Falkland Islands (Malvinas)",
    nameTr: "Falkland Adaları (Malvinas)",
  },
  { code: "FO", nameEn: "Faroe Islands", nameTr: "Faroe Adaları" },
  { code: "FJ", nameEn: "Fiji", nameTr: "Fiji" },
  { code: "FI", nameEn: "Finland", nameTr: "Finlandiya" },
  { code: "FR", nameEn: "France", nameTr: "Fransa" },
  { code: "GF", nameEn: "French Guiana", nameTr: "Fransız Guyanası" },
  { code: "PF", nameEn: "French Polynesia", nameTr: "Fransız Polinezyası" },
  {
    code: "TF",
    nameEn: "French Southern Territories",
    nameTr: "Fransız Güney ve Antarktik Toprakları",
  },
  { code: "GA", nameEn: "Gabon", nameTr: "Gabon" },
  { code: "GM", nameEn: "Gambia", nameTr: "Gambiya" },
  { code: "GE", nameEn: "Georgia", nameTr: "Gürcistan" },
  { code: "DE", nameEn: "Germany", nameTr: "Almanya" },
  { code: "GH", nameEn: "Ghana", nameTr: "Gana" },
  { code: "GI", nameEn: "Gibraltar", nameTr: "Cebelitarık" },
  { code: "GR", nameEn: "Greece", nameTr: "Yunanistan" },
  { code: "GL", nameEn: "Greenland", nameTr: "Grönland" },
  { code: "GD", nameEn: "Grenada", nameTr: "Grenada" },
  { code: "GP", nameEn: "Guadeloupe", nameTr: "Guadeloupe" },
  { code: "GU", nameEn: "Guam", nameTr: "Guam" },
  { code: "GT", nameEn: "Guatemala", nameTr: "Guatemala" },
  { code: "GG", nameEn: "Guernsey", nameTr: "Guernsey" },
  { code: "GN", nameEn: "Guinea", nameTr: "Gine" },
  { code: "GW", nameEn: "Guinea-Bissau", nameTr: "Gine-Bissau" },
  { code: "GY", nameEn: "Guyana", nameTr: "Guyana" },
  { code: "HT", nameEn: "Haiti", nameTr: "Haiti" },
  {
    code: "HM",
    nameEn: "Heard Island and Mcdonald Islands",
    nameTr: "Heard Adası ve McDonald Adaları",
  },
  { code: "VA", nameEn: "Holy See (Vatican City State)", nameTr: "Vatikan" },
  { code: "HN", nameEn: "Honduras", nameTr: "Honduras" },
  { code: "HK", nameEn: "Hong Kong", nameTr: "Hong Kong" },
  { code: "HU", nameEn: "Hungary", nameTr: "Macaristan" },
  { code: "IS", nameEn: "Iceland", nameTr: "İzlanda" },
  { code: "IN", nameEn: "India", nameTr: "Hindistan" },
  { code: "ID", nameEn: "Indonesia", nameTr: "Endonezya" },
  { code: "IR", nameEn: "Iran, Islamic Republic of", nameTr: "İran" },
  { code: "IQ", nameEn: "Iraq", nameTr: "Irak" },
  { code: "IE", nameEn: "Ireland", nameTr: "İrlanda" },
  { code: "IM", nameEn: "Isle of Man", nameTr: "Man Adası" },
  { code: "IT", nameEn: "Italy", nameTr: "İtalya" },
  { code: "JM", nameEn: "Jamaica", nameTr: "Jamaika" },
  { code: "JP", nameEn: "Japan", nameTr: "Japonya" },
  { code: "JE", nameEn: "Jersey", nameTr: "Jersey" },
  { code: "JO", nameEn: "Jordan", nameTr: "Ürdün" },
  { code: "KZ", nameEn: "Kazakhstan", nameTr: "Kazakistan" },
  { code: "KE", nameEn: "Kenya", nameTr: "Kenya" },
  { code: "KI", nameEn: "Kiribati", nameTr: "Kiribati" },
  {
    code: "KP",
    nameEn: "Korea, Democratic People's Republic of",
    nameTr: "Kuzey Kore",
  },
  { code: "KR", nameEn: "Korea, Republic of", nameTr: "Güney Kore" },
  { code: "KW", nameEn: "Kuwait", nameTr: "Kuveyt" },
  { code: "KG", nameEn: "Kyrgyzstan", nameTr: "Kırgızistan" },
  { code: "LA", nameEn: "Lao People's Democratic Republic", nameTr: "Laos" },
  { code: "LV", nameEn: "Latvia", nameTr: "Letonya" },
  { code: "LB", nameEn: "Lebanon", nameTr: "Lübnan" },
  { code: "LS", nameEn: "Lesotho", nameTr: "Lesotho" },
  { code: "LR", nameEn: "Liberia", nameTr: "Liberya" },
  { code: "LY", nameEn: "Libya", nameTr: "Libya" },
  { code: "LI", nameEn: "Liechtenstein", nameTr: "Lihtenştayn" },
  { code: "LT", nameEn: "Lithuania", nameTr: "Litvanya" },
  { code: "LU", nameEn: "Luxembourg", nameTr: "Lüksemburg" },
  { code: "MO", nameEn: "Macao", nameTr: "Makao" },
  { code: "MK", nameEn: "North Macedonia", nameTr: "Kuzey Makedonya" },
  { code: "MG", nameEn: "Madagascar", nameTr: "Madagaskar" },
  { code: "MW", nameEn: "Malawi", nameTr: "Malavi" },
  { code: "MY", nameEn: "Malaysia", nameTr: "Malezya" },
  { code: "MV", nameEn: "Maldives", nameTr: "Maldivler" },
  { code: "ML", nameEn: "Mali", nameTr: "Mali" },
  { code: "MT", nameEn: "Malta", nameTr: "Malta" },
  { code: "MH", nameEn: "Marshall Islands", nameTr: "Marshall Adaları" },
  { code: "MQ", nameEn: "Martinique", nameTr: "Martinik" },
  { code: "MR", nameEn: "Mauritania", nameTr: "Moritanya" },
  { code: "MU", nameEn: "Mauritius", nameTr: "Mauritius" },
  { code: "YT", nameEn: "Mayotte", nameTr: "Mayotte" },
  { code: "MX", nameEn: "Mexico", nameTr: "Meksika" },
  {
    code: "FM",
    nameEn: "Micronesia, Federated States of",
    nameTr: "Mikronezya",
  },
  { code: "MD", nameEn: "Moldova, Republic of", nameTr: "Moldova" },
  { code: "MC", nameEn: "Monaco", nameTr: "Monako" },
  { code: "MN", nameEn: "Mongolia", nameTr: "Moğolistan" },
  { code: "ME", nameEn: "Montenegro", nameTr: "Karadağ" },
  { code: "MS", nameEn: "Montserrat", nameTr: "Montserrat" },
  { code: "MA", nameEn: "Morocco", nameTr: "Fas" },
  { code: "MZ", nameEn: "Mozambique", nameTr: "Mozambik" },
  { code: "MM", nameEn: "Myanmar", nameTr: "Myanmar" },
  { code: "NA", nameEn: "Namibia", nameTr: "Namibya" },
  { code: "NR", nameEn: "Nauru", nameTr: "Nauru" },
  { code: "NP", nameEn: "Nepal", nameTr: "Nepal" },
  { code: "NL", nameEn: "Netherlands", nameTr: "Hollanda" },
  { code: "NC", nameEn: "New Caledonia", nameTr: "Yeni Kaledonya" },
  { code: "NZ", nameEn: "New Zealand", nameTr: "Yeni Zelanda" },
  { code: "NI", nameEn: "Nicaragua", nameTr: "Nikaragua" },
  { code: "NE", nameEn: "Niger", nameTr: "Nijer" },
  { code: "NG", nameEn: "Nigeria", nameTr: "Nijerya" },
  { code: "NU", nameEn: "Niue", nameTr: "Niue" },
  { code: "NF", nameEn: "Norfolk Island", nameTr: "Norfolk Adası" },
  {
    code: "MP",
    nameEn: "Northern Mariana Islands",
    nameTr: "Kuzey Mariana Adaları",
  },
  { code: "NO", nameEn: "Norway", nameTr: "Norveç" },
  { code: "OM", nameEn: "Oman", nameTr: "Umman" },
  { code: "PK", nameEn: "Pakistan", nameTr: "Pakistan" },
  { code: "PW", nameEn: "Palau", nameTr: "Palau" },
  { code: "PS", nameEn: "Palestine", nameTr: "Filistin" },
  { code: "PA", nameEn: "Panama", nameTr: "Panama" },
  { code: "PG", nameEn: "Papua New Guinea", nameTr: "Papua Yeni Gine" },
  { code: "PY", nameEn: "Paraguay", nameTr: "Paraguay" },
  { code: "PE", nameEn: "Peru", nameTr: "Peru" },
  { code: "PH", nameEn: "Philippines", nameTr: "Filipinler" },
  { code: "PN", nameEn: "Pitcairn", nameTr: "Pitcairn Adaları" },
  { code: "PL", nameEn: "Poland", nameTr: "Polonya" },
  { code: "PT", nameEn: "Portugal", nameTr: "Portekiz" },
  { code: "PR", nameEn: "Puerto Rico", nameTr: "Porto Riko" },
  { code: "QA", nameEn: "Qatar", nameTr: "Katar" },
  { code: "RE", nameEn: "Reunion", nameTr: "Reunion" },
  { code: "RO", nameEn: "Romania", nameTr: "Romanya" },
  { code: "RU", nameEn: "Russian Federation", nameTr: "Rusya" },
  { code: "RW", nameEn: "Rwanda", nameTr: "Ruanda" },
  { code: "BL", nameEn: "Saint Barthélemy", nameTr: "Saint Barthélemy" },
  { code: "SH", nameEn: "Saint Helena", nameTr: "Saint Helena" },
  {
    code: "KN",
    nameEn: "Saint Kitts and Nevis",
    nameTr: "Saint Kitts ve Nevis",
  },
  { code: "LC", nameEn: "Saint Lucia", nameTr: "Saint Lucia" },
  {
    code: "MF",
    nameEn: "Saint Martin (French part)",
    nameTr: "Saint Martin (Fransız kesimi)",
  },
  {
    code: "PM",
    nameEn: "Saint Pierre and Miquelon",
    nameTr: "Saint Pierre ve Miquelon",
  },
  {
    code: "VC",
    nameEn: "Saint Vincent and the Grenadines",
    nameTr: "Saint Vincent ve Grenadinler",
  },
  { code: "WS", nameEn: "Samoa", nameTr: "Samoa" },
  { code: "SM", nameEn: "San Marino", nameTr: "San Marino" },
  {
    code: "ST",
    nameEn: "Sao Tome and Principe",
    nameTr: "Sao Tome ve Principe",
  },
  { code: "SA", nameEn: "Saudi Arabia", nameTr: "Suudi Arabistan" },
  { code: "SN", nameEn: "Senegal", nameTr: "Senegal" },
  { code: "RS", nameEn: "Serbia", nameTr: "Sırbistan" },
  { code: "SC", nameEn: "Seychelles", nameTr: "Seyşeller" },
  { code: "SL", nameEn: "Sierra Leone", nameTr: "Sierra Leone" },
  { code: "SG", nameEn: "Singapore", nameTr: "Singapur" },
  {
    code: "SX",
    nameEn: "Sint Maarten (Dutch part)",
    nameTr: "Sint Maarten (Hollanda kesimi)",
  },
  { code: "SK", nameEn: "Slovakia", nameTr: "Slovakya" },
  { code: "SI", nameEn: "Slovenia", nameTr: "Slovenya" },
  { code: "SB", nameEn: "Solomon Islands", nameTr: "Solomon Adaları" },
  { code: "SO", nameEn: "Somalia", nameTr: "Somali" },
  { code: "ZA", nameEn: "South Africa", nameTr: "Güney Afrika" },
  {
    code: "GS",
    nameEn: "South Georgia and the South Sandwich Islands",
    nameTr: "Güney Georgia ve Güney Sandwich Adaları",
  },
  { code: "SS", nameEn: "South Sudan", nameTr: "Güney Sudan" },
  { code: "ES", nameEn: "Spain", nameTr: "İspanya" },
  { code: "LK", nameEn: "Sri Lanka", nameTr: "Sri Lanka" },
  { code: "SD", nameEn: "Sudan", nameTr: "Sudan" },
  { code: "SR", nameEn: "Suriname", nameTr: "Surinam" },
  {
    code: "SJ",
    nameEn: "Svalbard and Jan Mayen",
    nameTr: "Svalbard ve Jan Mayen",
  },
  { code: "SZ", nameEn: "Eswatini", nameTr: "Esvatini" },
  { code: "SE", nameEn: "Sweden", nameTr: "İsveç" },
  { code: "CH", nameEn: "Switzerland", nameTr: "İsviçre" },
  { code: "SY", nameEn: "Syrian Arab Republic", nameTr: "Suriye" },
  { code: "TW", nameEn: "Taiwan", nameTr: "Tayvan" },
  { code: "TJ", nameEn: "Tajikistan", nameTr: "Tacikistan" },
  { code: "TZ", nameEn: "Tanzania, United Republic of", nameTr: "Tanzanya" },
  { code: "TH", nameEn: "Thailand", nameTr: "Tayland" },
  { code: "TL", nameEn: "Timor-Leste", nameTr: "Doğu Timor" },
  { code: "TG", nameEn: "Togo", nameTr: "Togo" },
  { code: "TK", nameEn: "Tokelau", nameTr: "Tokelau" },
  { code: "TO", nameEn: "Tonga", nameTr: "Tonga" },
  { code: "TT", nameEn: "Trinidad and Tobago", nameTr: "Trinidad ve Tobago" },
  { code: "TN", nameEn: "Tunisia", nameTr: "Tunus" },
  { code: "TR", nameEn: "Türkiye", nameTr: "Türkiye" },
  {
    code: "TRNC",
    nameEn: "North Cyprus (TRNC)",
    nameTr: "Kuzey Kıbrıs (KKTC)",
  },
  { code: "TM", nameEn: "Turkmenistan", nameTr: "Türkmenistan" },
  {
    code: "TC",
    nameEn: "Turks and Caicos Islands",
    nameTr: "Turks ve Caicos Adaları",
  },
  { code: "TV", nameEn: "Tuvalu", nameTr: "Tuvalu" },
  { code: "UG", nameEn: "Uganda", nameTr: "Uganda" },
  { code: "UA", nameEn: "Ukraine", nameTr: "Ukrayna" },
  {
    code: "AE",
    nameEn: "United Arab Emirates",
    nameTr: "Birleşik Arap Emirlikleri",
  },
  { code: "GB", nameEn: "United Kingdom", nameTr: "Birleşik Krallık" },
  {
    code: "US",
    nameEn: "United States",
    nameTr: "Amerika Birleşik Devletleri",
  },
  {
    code: "UM",
    nameEn: "United States Minor Outlying Islands",
    nameTr: "ABD Küçük Dış Adaları",
  },
  { code: "UY", nameEn: "Uruguay", nameTr: "Uruguay" },
  { code: "UZ", nameEn: "Uzbekistan", nameTr: "Özbekistan" },
  { code: "VU", nameEn: "Vanuatu", nameTr: "Vanuatu" },
  { code: "VE", nameEn: "Venezuela", nameTr: "Venezuela" },
  { code: "VN", nameEn: "Viet Nam", nameTr: "Vietnam" },
  {
    code: "VG",
    nameEn: "Virgin Islands, British",
    nameTr: "Britanya Virjin Adaları",
  },
  { code: "VI", nameEn: "Virgin Islands, U.S.", nameTr: "ABD Virjin Adaları" },
  { code: "WF", nameEn: "Wallis and Futuna", nameTr: "Wallis ve Futuna" },
  { code: "EH", nameEn: "Western Sahara", nameTr: "Batı Sahra" },
  { code: "YE", nameEn: "Yemen", nameTr: "Yemen" },
  { code: "ZM", nameEn: "Zambia", nameTr: "Zambiya" },
  { code: "ZW", nameEn: "Zimbabwe", nameTr: "Zimbabve" },
];
