import {
  Injectable,
  NotFoundException,
  BadRequestException,
  Logger,
  ForbiddenException,
  Inject,
  forwardRef,
} from '@nestjs/common';
import { UndoRepository } from '../repositories/undo.repository';
import { UsersRepository } from '../../users/repositories/users.repository';
import { LocationsRepository } from '../../locations/repositories/locations.repository';
import { InventoryRepository } from '../../inventory/repositories/inventory.repository';
import { DatabaseService } from '../../../core/database/database.service';
import { AuditUserContext } from '../../../common/interfaces/audit-user-context.interface';
import { UndoLog } from '../entities/undo-log.entity';
import { PoolClient } from 'pg';
import { UndoActionType } from '../../../common/enums/undo-action-type.enum';
import { PERMISSIONS } from '../../../common/constants/permissions';
import { SYSTEM_ROLES } from '../../../common/constants/system-roles';
import { NotificationsService } from '../../notifications/services/notifications.service';

@Injectable()
export class UndoService {
  private readonly logger = new Logger(UndoService.name);

  constructor(
    private readonly undoRepository: UndoRepository,
    private readonly usersRepository: UsersRepository,
    @Inject(forwardRef(() => LocationsRepository))
    private readonly locationsRepository: LocationsRepository,
    @Inject(forwardRef(() => InventoryRepository))
    private readonly inventoryRepository: InventoryRepository,
    private readonly db: DatabaseService,
    private readonly notificationsService: NotificationsService,
  ) {}

  // ===========================================================================
  // Public Methods
  // ===========================================================================

  async registerUndo(data: Partial<UndoLog>, client?: PoolClient): Promise<UndoLog> {
    return this.undoRepository.create(data, client);
  }

  async findLatest(context: AuditUserContext): Promise<UndoLog[]> {
    const isAdminRole = context.roles?.some((r) => r.name === SYSTEM_ROLES.ADMIN);
    const hasUndoAllPerm = context.permissions?.includes(PERMISSIONS.UNDO_ALL);

    // 1. Recovery Admin: Sees everything
    if (context.isRecoveryAdmin) {
      return this.undoRepository.findAllRecent(10, {
        excludeRecovery: false,
        excludeAdmins: false,
      });
    }

    // 2. Admin Role: Sees everything except Recovery Admin logs
    if (isAdminRole) {
      return this.undoRepository.findAllRecent(10, {
        excludeRecovery: true,
        excludeAdmins: false,
      });
    }

    // 3. User with undo.all (but no Admin role): Sees everything except Recovery Admin and Admin role logs
    if (hasUndoAllPerm) {
      return this.undoRepository.findAllRecent(10, {
        excludeRecovery: true,
        excludeAdmins: true,
      });
    }

    // 4. Regular Users: See only their own logs
    return this.undoRepository.findLatestForUser(context.userId);
  }

  async undo(id: string, context: AuditUserContext): Promise<void> {
    const log = await this.undoRepository.findById(id);
    if (!log) throw new NotFoundException('Undo log not found');
    if (log.undoneAt) throw new BadRequestException('This action has already been undone');
    if (new Date(log.expiresAt) < new Date())
      throw new BadRequestException('Undo period has expired');

    // CHECK PERMISSIONS
    const canUndo = await this.canUserUndo(log, context);
    if (!canUndo.allowed) {
      throw new ForbiddenException(canUndo.reason);
    }

    this.logger.log(
      { auditId: id, action: log.actionType, entity: log.entityType },
      'Performing undo',
    );

    await this.db.transaction(async (client) => {
      // 1. Perform Reversion
      await this.executeReversion(log, context.userId, client);

      // 2. Delete notifications that were generated by this action
      await this.notificationsService.deleteByUndoLogId(id, client);

      // 3. Mark as Undone
      await this.undoRepository.markAsUndone(id, context.userId, client);
    }, context);
  }

  // ===========================================================================
  // Private Helpers
  // ===========================================================================

  private async canUserUndo(
    log: UndoLog,
    context: AuditUserContext,
  ): Promise<{ allowed: boolean; reason?: string }> {
    const isRequestingAdmin =
      context.isRecoveryAdmin || context.roles?.some((r) => r.name === SYSTEM_ROLES.ADMIN);
    const hasUndoAll = isRequestingAdmin || context.permissions?.includes(PERMISSIONS.UNDO_ALL);
    const hasUndoOwn = context.permissions?.includes(PERMISSIONS.UNDO_OWN);

    // 1. Own Action
    if (log.userId === context.userId) {
      if (hasUndoOwn || hasUndoAll) {
        return { allowed: true };
      }
      return { allowed: false, reason: 'You do not have permission to undo your own actions.' };
    }

    // 2. Undo All (with restrictions)
    if (hasUndoAll) {
      const logOwner = await this.usersRepository.findById(log.userId);
      if (!logOwner) return { allowed: false, reason: 'Original user not found' };

      // Protection: Cannot undo actions of Recovery Admin or Admin
      if (logOwner.isRecoveryAdmin) {
        return { allowed: false, reason: 'Cannot undo actions performed by Recovery Admin.' };
      }

      if (logOwner.roles?.some((r) => r.name === SYSTEM_ROLES.ADMIN)) {
        return { allowed: false, reason: 'Cannot undo actions performed by an Administrator.' };
      }

      return { allowed: true };
    }

    return { allowed: false, reason: 'Permission denied.' };
  }

  private async executeReversion(
    log: UndoLog,
    undoUserId: string,
    client: PoolClient,
  ): Promise<void> {
    switch (log.actionType) {
      // Locations
      case UndoActionType.CREATE_LOCATION:
        return this.undoCreateLocation(log, client);
      case UndoActionType.UPDATE_LOCATION:
        return this.undoUpdateLocation(log, client);
      case UndoActionType.DELETE_LOCATION:
        return this.undoDeleteLocation(log, client);
      case UndoActionType.UPDATE_GENDER_LOCK:
        return this.undoUpdateGenderLock(log, client);
      case UndoActionType.UPDATE_GUEST_ZONE:
        return this.undoUpdateGuestZone(log, client);
      case UndoActionType.UPDATE_TR_ONLY:
        return this.undoUpdateTrOnly(log, client);
      case UndoActionType.UPDATE_FOREIGNER_ONLY:
        return this.undoUpdateForeignerOnly(log, client);
      case UndoActionType.UPDATE_IS_RECTORATE:
        return this.undoUpdateIsRectorate(log, client);

      // Beds
      case UndoActionType.CREATE_BED:
        return this.undoCreateBed(log, client);
      case UndoActionType.DELETE_BED:
        return this.undoDeleteBed(log, client);
      case UndoActionType.UPDATE_BED:
        return this.undoUpdateBed(log, client);
      case UndoActionType.UPDATE_BED_STATUS:
        return this.undoUpdateBedStatus(log, client);
      case UndoActionType.UPDATE_BED_TR_ONLY:
        return this.undoUpdateBedTrOnly(log, client);
      case UndoActionType.UPDATE_BED_FOREIGNER_ONLY:
        return this.undoUpdateBedForeignerOnly(log, client);
      case UndoActionType.UPDATE_BED_IS_RECTORATE:
        return this.undoUpdateBedIsRectorate(log, client);
      case UndoActionType.UPDATE_BED_GUEST_ZONE:
        return this.undoUpdateBedGuestZone(log, client);

      // Students
      case UndoActionType.DELETE_STUDENT:
        return this.undoDeleteStudent(log, client);

      case UndoActionType.UPDATE_STUDENT:
        return this.undoUpdateStudent(log, client);

      // Users
      case UndoActionType.DELETE_USER:
        return this.undoDeleteUser(log, client);

      case UndoActionType.UPDATE_USER:
        return this.undoUpdateUser(log, client);

      // Access
      case UndoActionType.ASSIGN_ROLE:
        return this.undoAssignRole(log, client);
      case UndoActionType.REVOKE_ROLE:
        return this.undoRevokeRole(log, client);
      case UndoActionType.ASSIGN_STAFF_LOCATION:
        return this.undoAssignStaffLocation(log, client);
      case UndoActionType.REVOKE_STAFF_LOCATION:
        return this.undoRevokeStaffLocation(log, client);

      // Semesters
      case UndoActionType.CREATE_SEMESTER:
        return this.undoCreateSemester(log, client);
      case UndoActionType.DELETE_SEMESTER:
        return this.undoDeleteSemester(log, client);
      case UndoActionType.UPDATE_SEMESTER:
        return this.undoUpdateSemester(log, client);
      case UndoActionType.UPDATE_SEMESTER_STATUS:
        return this.undoUpdateSemesterStatus(log, client);

      // Bookings
      case UndoActionType.CREATE_BOOKING:
        return this.undoCreateBooking(log, client);
      case UndoActionType.UPDATE_BOOKING:
        return this.undoUpdateBooking(log, client);
      case UndoActionType.CANCEL_BOOKING:
        return this.undoCancelBooking(log, client);
      case UndoActionType.CHECK_IN_BOOKING:
        return this.undoCheckInBooking(log, undoUserId, client);
      case UndoActionType.CHECK_OUT_BOOKING:
        return this.undoCheckOutBooking(log, undoUserId, client);
      case UndoActionType.APPROVE_BOOKING_FINANCIALS:
        return this.undoApproveBookingFinancials(log, client);
      case UndoActionType.REJECT_BOOKING:
        return this.undoRejectBooking(log, client);

      // Inventory Catalog
      case UndoActionType.CREATE_INVENTORY_CATALOG:
        return this.undoCreateInventoryCatalog(log, client);
      case UndoActionType.UPDATE_INVENTORY_CATALOG:
        return this.undoUpdateInventoryCatalog(log, client);
      case UndoActionType.DELETE_INVENTORY_CATALOG:
        return this.undoDeleteInventoryCatalog(log, client);

      // Inventory Templates
      case UndoActionType.UPDATE_INVENTORY_TEMPLATE:
        return this.undoUpdateTemplate(log, client);
      case UndoActionType.DELETE_INVENTORY_TEMPLATE:
        return this.undoDeleteTemplate(log, client);

      // Inventory Assignments
      case UndoActionType.CREATE_INVENTORY_ASSIGNMENT:
        return this.undoCreateInventoryAssignment(log, client);
      case UndoActionType.UPDATE_INVENTORY_ASSIGNMENT:
        return this.undoUpdateInventoryAssignment(log, client);
      case UndoActionType.DELETE_INVENTORY_ASSIGNMENT:
        return this.undoDeleteInventoryAssignment(log, client);
      case UndoActionType.APPLY_INVENTORY_TEMPLATE:
        return this.undoApplyInventoryTemplate(log, client);

      // Access Cards
      case UndoActionType.CREATE_CARD_BATCH:
        return this.undoCreateCardBatch(log, client);
      case UndoActionType.ISSUE_CARD:
        return this.undoIssueCard(log, undoUserId, client);
      case UndoActionType.RETURN_CARD:
        return this.undoReturnCard(log, undoUserId, client);
      case UndoActionType.MARK_CARD_LOST:
      case UndoActionType.MARK_CARD_BROKEN:
        return this.undoMarkCardQuarantined(log, undoUserId, client);
      case UndoActionType.REINSTATE_CARD:
        return this.undoReinstateCard(log, undoUserId, client);

      // Damages
      case UndoActionType.CREATE_DAMAGE_REPORT:
        return this.undoCreateDamageReport(log, client);
      case UndoActionType.APPROVE_DAMAGE_REPORT:
        return this.undoApproveDamageReport(log, client);
      case UndoActionType.REJECT_DAMAGE_REPORT:
        return this.undoRejectDamageReport(log, client);

      // Bulk Import
      case UndoActionType.BULK_IMPORT_STUDENT:
        return this.undoBulkImport(log, client);

      // Student Applications
      case UndoActionType.APPROVE_APPLICATION:
        return this.undoApproveApplication(log, client);
      case UndoActionType.REJECT_APPLICATION:
        return this.undoRejectApplication(log, client);

      // Pre-Reservations
      case UndoActionType.ASSIGN_PRE_RESERVATION:
        return this.undoAssignPreReservation(log, client);
      case UndoActionType.REJECT_PRE_RESERVATION:
        return this.undoRejectPreReservation(log, client);

      // Room Changes
      case UndoActionType.RESOLVE_ROOM_CHANGE:
        return this.undoResolveRoomChange(log, client);
      case UndoActionType.APPROVE_ROOM_CHANGE_PAYMENT:
        return this.undoApproveRoomChangePayment(log, client);
      case UndoActionType.STAFF_MOVE_BED:
        return this.undoStaffMoveBed(log, client);

      // Dorm Certificates
      case UndoActionType.APPROVE_DORM_CERT:
        return this.undoApproveDormCert(log, client);
      case UndoActionType.REJECT_DORM_CERT:
        return this.undoRejectDormCert(log, client);

      // Announcements
      case UndoActionType.CREATE_ANNOUNCEMENT:
        return this.undoCreateAnnouncement(log, client);
      case UndoActionType.UPDATE_ANNOUNCEMENT:
        return this.undoUpdateAnnouncement(log, client);
      case UndoActionType.DELETE_ANNOUNCEMENT:
        return this.undoDeleteAnnouncement(log, client);
      case UndoActionType.PUBLISH_ANNOUNCEMENT:
        return this.undoPublishAnnouncement(log, client);
      case UndoActionType.UNPUBLISH_ANNOUNCEMENT:
        return this.undoUnpublishAnnouncement(log, client);

      // Room Types
      case UndoActionType.CREATE_ROOM_TYPE:
        return this.undoCreateRoomType(log, client);
      case UndoActionType.UPDATE_ROOM_TYPE:
        return this.undoUpdateRoomType(log, client);
      case UndoActionType.DELETE_ROOM_TYPE:
        return this.undoDeleteRoomType(log, client);

      // Guest Stays
      case UndoActionType.CREATE_GUEST_STAY:
        return this.undoCreateGuestStay(log, client);
      case UndoActionType.CHECK_IN_GUEST_STAY:
        return this.undoCheckInGuestStay(log, client);
      case UndoActionType.CHECK_OUT_GUEST_STAY:
        return this.undoCheckOutGuestStay(log, client);
      case UndoActionType.CANCEL_GUEST_STAY:
        return this.undoCancelGuestStay(log, client);

      default:
        throw new BadRequestException(`Unsupported undo action: ${log.actionType}`);
    }
  }

  private camelToSnake(str: string): string {
    return str.replace(/[A-Z]/g, (letter) => `_${letter.toLowerCase()}`);
  }

  // ===========================================================================
  // Location Handlers
  // ===========================================================================

  private async undoCreateLocation(log: UndoLog, client: PoolClient): Promise<void> {
    const locationId = parseInt(log.entityId, 10);
    const exists = await client.query('SELECT 1 FROM locations WHERE id = $1', [locationId]);
    if (exists.rowCount === 0) throw new BadRequestException('Location does not exist');
    await client.query('UPDATE locations SET deleted_at = NOW() WHERE id = $1', [locationId]);
  }

  private async undoDeleteLocation(log: UndoLog, client: PoolClient): Promise<void> {
    const locationId = parseInt(log.entityId, 10);
    const location = await client.query(
      'SELECT id, tree_path::TEXT as tree_path, deleted_at FROM locations WHERE id = $1',
      [locationId],
    );
    if (location.rowCount === 0) throw new BadRequestException('Location does not exist');
    if (!location.rows[0].deleted_at) throw new BadRequestException('Location is not deleted');

    const treePath = location.rows[0].tree_path;
    if (treePath.includes('.')) {
      const parentPath = treePath.substring(0, treePath.lastIndexOf('.'));
      const parent = await client.query(
        'SELECT 1 FROM locations WHERE tree_path::TEXT = $1 AND deleted_at IS NULL',
        [parentPath],
      );
      if (parent.rowCount === 0)
        throw new BadRequestException('Cannot restore: parent location is deleted or missing');
    }

    // Compare deleted_at entirely in the database to avoid JavaScript Date
    // millisecond truncation of PostgreSQL's microsecond-precision timestamps.
    await client.query(
      `UPDATE locations SET deleted_at = NULL
       WHERE tree_path <@ $1::ltree
         AND deleted_at = (SELECT deleted_at FROM locations WHERE id = $2)`,
      [treePath, locationId],
    );
    await client.query(
      `UPDATE beds SET deleted_at = NULL
       WHERE location_id IN (SELECT id FROM locations WHERE tree_path <@ $1::ltree)
         AND deleted_at = (SELECT deleted_at FROM locations WHERE id = $2)`,
      [treePath, locationId],
    );
  }

  private async undoUpdateLocation(log: UndoLog, client: PoolClient): Promise<void> {
    const locationId = parseInt(log.entityId, 10);
    const data = log.undoData;

    const allowedFields = {
      name: 'name',
      type: 'type',
      basePrice: 'base_price',
    };

    const updates: string[] = [];
    const values: any[] = [];
    let paramIndex = 1;

    for (const [camelKey, snakeKey] of Object.entries(allowedFields)) {
      if (data[camelKey] !== undefined) {
        updates.push(`${snakeKey} = $${paramIndex++}`);
        values.push(data[camelKey]);
      }
    }

    if (updates.length === 0) return;

    values.push(locationId);
    const query = `
      UPDATE locations 
      SET ${updates.join(', ')}, updated_at = NOW()
      WHERE id = $${paramIndex} AND deleted_at IS NULL
    `;

    const res = await client.query(query, values);
    if (res.rowCount === 0) throw new BadRequestException('Location not found or is deleted');
  }

  private async undoUpdateGenderLock(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousGenderLock, cascade } = log.undoData;
    const locationId = parseInt(log.entityId, 10);

    const location = await client.query('SELECT tree_path FROM locations WHERE id = $1', [
      locationId,
    ]);
    if (location.rowCount === 0) return;
    const treePath = location.rows[0].tree_path;

    if (cascade) {
      await client.query(
        `UPDATE locations SET gender_lock = $1, updated_at = NOW() WHERE tree_path <@ $2 AND deleted_at IS NULL`,
        [previousGenderLock, treePath],
      );
    } else {
      await client.query(
        `UPDATE locations SET gender_lock = $1, updated_at = NOW() WHERE id = $2 AND deleted_at IS NULL`,
        [previousGenderLock, locationId],
      );
    }
  }

  private async undoUpdateGuestZone(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousGuestZone, cascade } = log.undoData;
    const locationId = parseInt(log.entityId, 10);

    const location = await client.query('SELECT tree_path FROM locations WHERE id = $1', [
      locationId,
    ]);
    if (location.rowCount === 0) return;
    const treePath = location.rows[0].tree_path;

    if (cascade) {
      await client.query(
        `UPDATE locations SET is_guest_zone = $1, updated_at = NOW() WHERE tree_path <@ $2 AND deleted_at IS NULL`,
        [previousGuestZone, treePath],
      );
      await client.query(
        `UPDATE beds SET is_guest_zone = $1 WHERE location_id IN (SELECT id FROM locations WHERE tree_path <@ $2) AND deleted_at IS NULL`,
        [previousGuestZone, treePath],
      );
    } else {
      await client.query(
        `UPDATE locations SET is_guest_zone = $1, updated_at = NOW() WHERE id = $2 AND deleted_at IS NULL`,
        [previousGuestZone, locationId],
      );
      await client.query(
        `UPDATE beds SET is_guest_zone = $1 WHERE location_id = $2 AND deleted_at IS NULL`,
        [previousGuestZone, locationId],
      );
    }
  }

  private async undoUpdateTrOnly(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousTrOnly, cascade } = log.undoData;
    const locationId = parseInt(log.entityId, 10);

    const location = await client.query('SELECT tree_path FROM locations WHERE id = $1', [
      locationId,
    ]);
    if (location.rowCount === 0) return;
    const treePath = location.rows[0].tree_path;

    if (cascade) {
      await client.query(
        `UPDATE locations SET is_tr_only = $1, updated_at = NOW() WHERE tree_path <@ $2 AND deleted_at IS NULL`,
        [previousTrOnly, treePath],
      );
      await client.query(
        `UPDATE beds SET is_tr_only = $1 WHERE location_id IN (SELECT id FROM locations WHERE tree_path <@ $2) AND deleted_at IS NULL`,
        [previousTrOnly, treePath],
      );
    } else {
      await client.query(
        `UPDATE locations SET is_tr_only = $1, updated_at = NOW() WHERE id = $2 AND deleted_at IS NULL`,
        [previousTrOnly, locationId],
      );
      await client.query(
        `UPDATE beds SET is_tr_only = $1 WHERE location_id = $2 AND deleted_at IS NULL`,
        [previousTrOnly, locationId],
      );
    }
  }

  private async undoUpdateForeignerOnly(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousForeignerOnly, cascade } = log.undoData;
    const locationId = parseInt(log.entityId, 10);

    const location = await client.query('SELECT tree_path FROM locations WHERE id = $1', [
      locationId,
    ]);
    if (location.rowCount === 0) return;
    const treePath = location.rows[0].tree_path;

    if (cascade) {
      await client.query(
        `UPDATE locations SET is_foreigner_only = $1, updated_at = NOW() WHERE tree_path <@ $2 AND deleted_at IS NULL`,
        [previousForeignerOnly, treePath],
      );
      await client.query(
        `UPDATE beds SET is_foreigner_only = $1 WHERE location_id IN (SELECT id FROM locations WHERE tree_path <@ $2) AND deleted_at IS NULL`,
        [previousForeignerOnly, treePath],
      );
    } else {
      await client.query(
        `UPDATE locations SET is_foreigner_only = $1, updated_at = NOW() WHERE id = $2 AND deleted_at IS NULL`,
        [previousForeignerOnly, locationId],
      );
      await client.query(
        `UPDATE beds SET is_foreigner_only = $1 WHERE location_id = $2 AND deleted_at IS NULL`,
        [previousForeignerOnly, locationId],
      );
    }
  }

  private async undoUpdateIsRectorate(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousIsRectorate, cascade } = log.undoData;
    const locationId = parseInt(log.entityId, 10);

    const location = await client.query('SELECT tree_path FROM locations WHERE id = $1', [
      locationId,
    ]);
    if (location.rowCount === 0) return;
    const treePath = location.rows[0].tree_path;

    if (cascade) {
      await client.query(
        `UPDATE locations SET is_rectorate = $1, updated_at = NOW() WHERE tree_path <@ $2 AND deleted_at IS NULL`,
        [previousIsRectorate, treePath],
      );
      await client.query(
        `UPDATE beds SET is_rectorate = $1 WHERE location_id IN (SELECT id FROM locations WHERE tree_path <@ $2) AND deleted_at IS NULL`,
        [previousIsRectorate, treePath],
      );
    } else {
      await client.query(
        `UPDATE locations SET is_rectorate = $1, updated_at = NOW() WHERE id = $2 AND deleted_at IS NULL`,
        [previousIsRectorate, locationId],
      );
      await client.query(
        `UPDATE beds SET is_rectorate = $1 WHERE location_id = $2 AND deleted_at IS NULL`,
        [previousIsRectorate, locationId],
      );
    }
  }

  // ===========================================================================
  // Bed Handlers
  // ===========================================================================

  private async undoCreateBed(log: UndoLog, client: PoolClient): Promise<void> {
    const bedId = parseInt(log.entityId, 10);
    await client.query('UPDATE beds SET deleted_at = NOW() WHERE id = $1', [bedId]);
  }

  private async undoDeleteBed(log: UndoLog, client: PoolClient): Promise<void> {
    const bedId = parseInt(log.entityId, 10);
    const bed = await client.query('SELECT id, location_id, deleted_at FROM beds WHERE id = $1', [
      bedId,
    ]);
    if (bed.rowCount === 0) throw new BadRequestException('Bed does not exist');
    if (!bed.rows[0].deleted_at) throw new BadRequestException('Bed is not deleted');

    const locationId = bed.rows[0].location_id;
    const loc = await client.query('SELECT 1 FROM locations WHERE id = $1 AND deleted_at IS NULL', [
      locationId,
    ]);
    if (loc.rowCount === 0)
      throw new BadRequestException('Cannot restore bed: parent location is deleted');

    await client.query('UPDATE beds SET deleted_at = NULL WHERE id = $1', [bedId]);
  }

  private async undoUpdateBed(log: UndoLog, client: PoolClient): Promise<void> {
    const id = parseInt(log.entityId, 10);
    const data = log.undoData;

    const allowedFields = {
      label: 'label',
      locationId: 'location_id',
      status: 'status',
    };

    const updates: string[] = [];
    const values: any[] = [];
    let paramIndex = 1;

    for (const [camelKey, snakeKey] of Object.entries(allowedFields)) {
      if (data[camelKey] !== undefined) {
        updates.push(`${snakeKey} = $${paramIndex++}`);
        values.push(data[camelKey]);
      }
    }

    if (updates.length === 0) return;

    values.push(id);
    const res = await client.query(
      `UPDATE beds SET ${updates.join(', ')} WHERE id = $${paramIndex} AND deleted_at IS NULL`,
      values,
    );
    if (res.rowCount === 0) throw new BadRequestException('Bed not found or is deleted');
  }

  private async undoUpdateBedStatus(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousStatus } = log.undoData;
    const bedId = parseInt(log.entityId, 10);
    const res = await client.query(
      'UPDATE beds SET status = $1 WHERE id = $2 AND deleted_at IS NULL',
      [previousStatus, bedId],
    );
    if (res.rowCount === 0) throw new BadRequestException('Bed not found or is deleted');
  }

  private async undoUpdateBedTrOnly(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousTrOnly } = log.undoData;
    const bedId = parseInt(log.entityId, 10);
    await client.query('UPDATE beds SET is_tr_only = $1 WHERE id = $2', [previousTrOnly, bedId]);
  }

  private async undoUpdateBedForeignerOnly(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousForeignerOnly } = log.undoData;
    const bedId = parseInt(log.entityId, 10);
    await client.query('UPDATE beds SET is_foreigner_only = $1 WHERE id = $2', [
      previousForeignerOnly,
      bedId,
    ]);
  }

  private async undoUpdateBedIsRectorate(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousIsRectorate } = log.undoData;
    const bedId = parseInt(log.entityId, 10);
    await client.query('UPDATE beds SET is_rectorate = $1 WHERE id = $2', [
      previousIsRectorate,
      bedId,
    ]);
  }

  private async undoUpdateBedGuestZone(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousGuestZone } = log.undoData;
    const bedId = parseInt(log.entityId, 10);
    await client.query('UPDATE beds SET is_guest_zone = $1 WHERE id = $2', [
      previousGuestZone,
      bedId,
    ]);
  }

  // ===========================================================================
  // Student Handlers
  // ===========================================================================

  private async undoDeleteStudent(log: UndoLog, client: PoolClient): Promise<void> {
    const studentId = log.entityId; // UUID
    const student = await client.query('SELECT id, deleted_at FROM students WHERE id = $1', [
      studentId,
    ]);

    if (student.rowCount === 0) throw new BadRequestException('Student does not exist');
    if (!student.rows[0].deleted_at) throw new BadRequestException('Student is not deleted');

    await client.query('UPDATE students SET deleted_at = NULL WHERE id = $1', [studentId]);
  }

  private async undoUpdateStudent(log: UndoLog, client: PoolClient): Promise<void> {
    const studentId = log.entityId;
    const data = log.undoData;

    const allowedFields = {
      firstName: 'first_name',
      lastName: 'last_name',
      studentNumber: 'student_number',
      gender: 'gender',
      nationalityCode: 'nationality_code',
      nationalId: 'national_id',
      birthDate: 'birth_date',
      birthPlace: 'birth_place',
      department: 'department',
      email: 'email',
      phoneNumber: 'phone_number',
      isActive: 'is_active',
    };

    const updates: string[] = [];
    const values: any[] = [];
    let paramIndex = 1;

    for (const [camelKey, snakeKey] of Object.entries(allowedFields)) {
      if (data[camelKey] !== undefined) {
        updates.push(`${snakeKey} = $${paramIndex++}`);
        values.push(data[camelKey]);
      }
    }

    if (updates.length === 0) return;

    values.push(studentId);
    const res = await client.query(
      `UPDATE students SET ${updates.join(', ')}, updated_at = NOW() WHERE id = $${paramIndex}`,
      values,
    );
    if (res.rowCount === 0) throw new BadRequestException('Student not found or is deleted');
  }

  // ===========================================================================
  // User Handlers
  // ===========================================================================

  private async undoDeleteUser(log: UndoLog, client: PoolClient): Promise<void> {
    const userId = log.entityId; // UUID
    const user = await client.query('SELECT id, deleted_at FROM users WHERE id = $1', [userId]);

    if (user.rowCount === 0) throw new BadRequestException('User does not exist');
    if (!user.rows[0].deleted_at) throw new BadRequestException('User is not deleted');

    await client.query('UPDATE users SET deleted_at = NULL WHERE id = $1', [userId]);
  }

  private async undoUpdateUser(log: UndoLog, client: PoolClient): Promise<void> {
    const userId = log.entityId;
    const data = log.undoData;

    const allowedFields = {
      email: 'email',
      firstName: 'first_name',
      lastName: 'last_name',
      phoneNumber: 'phone_number',
      isActive: 'is_active',
    };

    const updates: string[] = [];
    const values: any[] = [];
    let paramIndex = 1;

    for (const [camelKey, snakeKey] of Object.entries(allowedFields)) {
      if (data[camelKey] !== undefined) {
        updates.push(`${snakeKey} = $${paramIndex++}`);
        values.push(data[camelKey]);
      }
    }

    if (updates.length === 0) return;

    values.push(userId);
    const res = await client.query(
      `UPDATE users SET ${updates.join(', ')}, updated_at = NOW() WHERE id = $${paramIndex}`,
      values,
    );
    if (res.rowCount === 0) throw new BadRequestException('User not found or is deleted');
  }

  // ===========================================================================
  // Access Handlers (Roles)
  // ===========================================================================

  private async undoAssignRole(log: UndoLog, client: PoolClient): Promise<void> {
    const userId = log.entityId;
    const { roleId } = log.undoData;
    await client.query('DELETE FROM user_roles WHERE user_id = $1 AND role_id = $2', [
      userId,
      roleId,
    ]);
  }

  private async undoRevokeRole(log: UndoLog, client: PoolClient): Promise<void> {
    const userId = log.entityId;
    const { roleId } = log.undoData;
    await client.query(
      'INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2) ON CONFLICT DO NOTHING',
      [userId, roleId],
    );
  }

  private async undoAssignStaffLocation(log: UndoLog, client: PoolClient): Promise<void> {
    const userId = log.entityId;
    const { locationId } = log.undoData;
    await client.query('DELETE FROM staff_locations WHERE user_id = $1 AND location_id = $2', [
      userId,
      locationId,
    ]);
  }

  private async undoRevokeStaffLocation(log: UndoLog, client: PoolClient): Promise<void> {
    const userId = log.entityId;
    const { locationId } = log.undoData;
    await client.query(
      'INSERT INTO staff_locations (user_id, location_id) VALUES ($1, $2) ON CONFLICT DO NOTHING',
      [userId, locationId],
    );
  }

  // ===========================================================================
  // Semester Handlers
  // ===========================================================================

  private async undoCreateSemester(log: UndoLog, client: PoolClient): Promise<void> {
    const semesterId = parseInt(log.entityId, 10);
    // Assuming hard delete for clean undo of creation
    await client.query('DELETE FROM semesters WHERE id = $1', [semesterId]);
  }

  private async undoDeleteSemester(log: UndoLog, client: PoolClient): Promise<void> {
    const semesterId = parseInt(log.entityId, 10);
    const { id, createdAt, updatedAt, ...data } = log.undoData;

    const keys = Object.keys(data);
    keys.forEach((key) => {
      if (!/^[a-zA-Z0-9_]+$/.test(key)) {
        throw new BadRequestException(`Invalid column name in undo data: ${key}`);
      }
    });

    const columns = keys.map((k) => `"${this.camelToSnake(k)}"`).join(', ');
    const values = keys.map((k) => data[k]);
    const placeholders = values.map((_, i) => `$${i + 1}`).join(', ');

    await client.query(
      `INSERT INTO semesters (id, ${columns}) VALUES (${semesterId}, ${placeholders})`,
      values,
    );
  }

  private async undoUpdateSemester(log: UndoLog, client: PoolClient): Promise<void> {
    const id = parseInt(log.entityId, 10);
    const data = log.undoData;

    const allowedFields = {
      type: 'type',
      academicYear: 'academic_year',
      displayName: 'display_name',
      startDate: 'start_date',
      endDate: 'end_date',
      bookingStartDate: 'booking_start_date',
      bookingEndDate: 'booking_end_date',
      depositAmountTry: 'deposit_amount_try',
      depositAmountForeign: 'deposit_amount_foreign',
      foreignCurrencyCode: 'foreign_currency_code',
      paymentDeadlineDate: 'payment_deadline_date',
      status: 'status',
    };

    const updates: string[] = [];
    const values: any[] = [];
    let paramIndex = 1;

    for (const [camelKey, snakeKey] of Object.entries(allowedFields)) {
      if (data[camelKey] !== undefined) {
        updates.push(`${snakeKey} = $${paramIndex++}`);
        values.push(data[camelKey]);
      }
    }

    if (updates.length === 0) return;

    values.push(id);
    const res = await client.query(
      `UPDATE semesters SET ${updates.join(', ')}, updated_at = NOW() WHERE id = $${paramIndex}`,
      values,
    );
    if (res.rowCount === 0) throw new BadRequestException('Semester not found');
  }

  private async undoUpdateSemesterStatus(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousStatus } = log.undoData;
    const id = parseInt(log.entityId, 10);
    const res = await client.query('UPDATE semesters SET status = $1 WHERE id = $2', [
      previousStatus,
      id,
    ]);
    if (res.rowCount === 0) throw new BadRequestException('Semester not found');
  }

  // ===========================================================================
  // Booking Handlers
  // ===========================================================================

  private async undoCreateBooking(log: UndoLog, client: PoolClient): Promise<void> {
    const bookingId = log.entityId;

    // 1. Get locationId before deletion
    const bookingRes = await client.query(
      'SELECT bd.location_id FROM bookings bo JOIN beds bd ON bo.bed_id = bd.id WHERE bo.id = $1',
      [bookingId],
    );

    // 2. Delete the booking
    await client.query('DELETE FROM bookings WHERE id = $1', [bookingId]);

    // 3. Clear gender lock if room is now empty
    if (bookingRes.rows.length > 0) {
      const locationId = bookingRes.rows[0].location_id;
      await this.locationsRepository.clearGenderLockIfEmpty(locationId, client);
    }
  }

  private async undoUpdateBooking(log: UndoLog, client: PoolClient): Promise<void> {
    const id = log.entityId;
    const data = log.undoData;

    const allowedFields = {
      startDate: 'start_date',
      endDate: 'end_date',
      status: 'status',
      paymentStatus: 'payment_status',
      checkedInAt: 'checked_in_at',
      checkedOutAt: 'checked_out_at',
      contractSigned: 'contract_signed',
      contractUrl: 'contract_url',
    };

    const updates: string[] = [];
    const values: any[] = [];
    let paramIndex = 1;

    for (const [camelKey, snakeKey] of Object.entries(allowedFields)) {
      if (data[camelKey] !== undefined) {
        updates.push(`${snakeKey} = $${paramIndex++}`);
        values.push(data[camelKey]);
      }
    }

    if (updates.length === 0) return;

    values.push(id);
    const res = await client.query(
      `UPDATE bookings SET ${updates.join(', ')}, updated_at = NOW() WHERE id = $${paramIndex}`,
      values,
    );
    if (res.rowCount === 0) throw new BadRequestException('Booking not found');
  }

  private async undoCancelBooking(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousStatus } = log.undoData;
    const bookingId = log.entityId;
    await client.query('UPDATE bookings SET status = $1 WHERE id = $2', [
      previousStatus,
      bookingId,
    ]);
  }

  private async undoCheckInBooking(
    log: UndoLog,
    undoUserId: string,
    client: PoolClient,
  ): Promise<void> {
    const { previousStatus, previousCheckInDate, bedId } = log.undoData;
    const bookingId = log.entityId;

    // 1. Revert Booking Status & Reset Contract Flag
    await client.query(
      'UPDATE bookings SET status = $1, checked_in_at = $2, contract_signed = FALSE WHERE id = $3',
      [previousStatus, previousCheckInDate, bookingId],
    );

    // 2. Mark Bed as Available
    if (bedId) {
      await client.query("UPDATE beds SET status = 'available' WHERE id = $1", [bedId]);

      // 2.1 Clear Gender Lock if room is now empty
      const bedRes = await client.query('SELECT location_id FROM beds WHERE id = $1', [bedId]);
      if (bedRes.rows.length > 0) {
        await this.locationsRepository.clearGenderLockIfEmpty(bedRes.rows[0].location_id, client);
      }
    }

    // 3. CLEANUP: Delete the inventory snapshots generated during check-in
    await client.query('DELETE FROM booking_inventory_snapshots WHERE booking_id = $1', [
      bookingId,
    ]);

    // 4. CONTRACT CLEANUP: Delete the generated contract
    await client.query('DELETE FROM booking_contracts WHERE booking_id = $1', [bookingId]);

    // 5. CARD REVERSION: If a card was issued during this check-in, return it to the pool
    const cardRes = await client.query(
      `UPDATE access_cards 
       SET status = 'available', 
           current_holder_id = NULL, 
           current_booking_id = NULL, 
           returned_at = NOW(),
           updated_at = NOW()
       WHERE current_booking_id = $1 AND status = 'active'
       RETURNING id, current_holder_id`,
      [bookingId],
    );

    if (cardRes.rows.length > 0) {
      for (const card of cardRes.rows) {
        await client.query(
          `INSERT INTO access_card_logs (card_id, student_id, booking_id, action_type, performed_by, notes)
           VALUES ($1, $2, $3, 'returned', $4, $5)`,
          [
            card.id,
            card.current_holder_id,
            bookingId,
            undoUserId,
            'Undo: Check-in reversed, card auto-returned',
          ],
        );
      }
    }
  }

  private async undoCheckOutBooking(
    log: UndoLog,
    undoUserId: string,
    client: PoolClient,
  ): Promise<void> {
    const { previousStatus, previousCheckedOutAt, bedId, cardId } = log.undoData;
    const bookingId = log.entityId;

    // 1. Revert Booking Status
    await client.query('UPDATE bookings SET status = $1, checked_out_at = $2 WHERE id = $3', [
      previousStatus,
      previousCheckedOutAt,
      bookingId,
    ]);

    // 2. Mark Bed as Occupied
    await client.query("UPDATE beds SET status = 'occupied' WHERE id = $1", [bedId]);

    // 3. Optional: Re-activate card if it was returned and is still available
    if (cardId) {
      const cardCheck = await client.query(
        'SELECT status, current_booking_id FROM access_cards WHERE id = $1 FOR UPDATE',
        [cardId],
      );
      if (cardCheck.rows[0] && cardCheck.rows[0].status === 'available') {
        // Find student ID
        const bRes = await client.query('SELECT student_id FROM bookings WHERE id = $1', [
          bookingId,
        ]);
        const studentId = bRes.rows[0].student_id;

        await client.query(
          `UPDATE access_cards 
           SET status = 'active', 
               current_holder_id = $1, 
               current_booking_id = $2, 
               returned_at = NULL,
               updated_at = NOW()
           WHERE id = $3`,
          [studentId, bookingId, cardId],
        );

        await client.query(
          `INSERT INTO access_card_logs (card_id, student_id, booking_id, action_type, performed_by, notes)
           VALUES ($1, $2, $3, 'issued', $4, $5)`,
          [cardId, studentId, bookingId, undoUserId, 'Undo: Check-out reversed, card re-activated'],
        );
      }
    }
  }

  private async undoApproveBookingFinancials(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousStatus, previousPaymentStatus } = log.undoData;
    const bookingId = log.entityId;
    // is_accounting_approved is derived from status: only ready_for_checkin/confirmed means approved
    const wasApproved = ['ready_for_checkin', 'confirmed'].includes(previousStatus);
    await client.query(
      'UPDATE bookings SET status = $1, payment_status = $2, is_accounting_approved = $3, accounting_approved_at = NULL, accounting_approved_by = NULL WHERE id = $4',
      [previousStatus, previousPaymentStatus, wasApproved, bookingId],
    );
  }

  private async undoRejectBooking(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousStatus } = log.undoData;
    const bookingId = log.entityId;
    await client.query('UPDATE bookings SET status = $1 WHERE id = $2', [
      previousStatus,
      bookingId,
    ]);
  }

  // ===========================================================================
  // Inventory Handlers
  // ===========================================================================

  private async undoCreateInventoryCatalog(log: UndoLog, client: PoolClient): Promise<void> {
    const id = parseInt(log.entityId, 10);
    await client.query('UPDATE inventory_catalog SET deleted_at = NOW() WHERE id = $1', [id]);
  }

  private async undoDeleteInventoryCatalog(log: UndoLog, client: PoolClient): Promise<void> {
    const id = parseInt(log.entityId, 10);
    await client.query('UPDATE inventory_catalog SET deleted_at = NULL WHERE id = $1', [id]);
  }

  private async undoUpdateInventoryCatalog(log: UndoLog, client: PoolClient): Promise<void> {
    const id = parseInt(log.entityId, 10);
    const data = log.undoData;

    const allowedFields = {
      nameTr: 'name_tr',
      nameEn: 'name_en',
      descriptionTr: 'description_tr',
      descriptionEn: 'description_en',
      scope: 'scope',
      basePriceTry: 'base_price_try',
      basePriceForeign: 'base_price_foreign',
      foreignCurrencyCode: 'foreign_currency_code',
      isActive: 'is_active',
      isOptional: 'is_optional',
    };

    const updates: string[] = [];
    const values: any[] = [];
    let paramIndex = 1;

    for (const [camelKey, snakeKey] of Object.entries(allowedFields)) {
      if (data[camelKey] !== undefined) {
        updates.push(`${snakeKey} = $${paramIndex++}`);
        values.push(data[camelKey]);
      }
    }

    if (updates.length === 0) return;

    values.push(id);
    const res = await client.query(
      `UPDATE inventory_catalog SET ${updates.join(', ')}, updated_at = NOW() WHERE id = $${paramIndex}`,
      values,
    );
    if (res.rowCount === 0) throw new BadRequestException('Catalog item not found');
  }

  private async undoUpdateTemplate(log: UndoLog, client: PoolClient): Promise<void> {
    const id = parseInt(log.entityId, 10);
    const { items, ...data } = log.undoData;

    // Use repository to restore both main fields and items
    await this.inventoryRepository.updateTemplate(
      id,
      {
        ...data,
        items: items.map((i: any) => ({ catalogId: i.catalogId, quantity: i.quantity })),
      },
      client,
    );
  }

  private async undoDeleteTemplate(log: UndoLog, client: PoolClient): Promise<void> {
    const id = parseInt(log.entityId, 10);
    await client.query('UPDATE inventory_templates SET deleted_at = NULL WHERE id = $1', [id]);
  }

  private async undoCreateInventoryAssignment(log: UndoLog, client: PoolClient): Promise<void> {
    const id = log.entityId;
    const { bulk, locationIds, bedIds, templateId } = log.undoData;

    if (bulk) {
      // Bulk reversal: Find all assignments created by this template apply operation
      // Since assignments don't have a direct link to the template, we use the IDs and time correlation or just trust the IDs
      if (locationIds && locationIds.length > 0) {
        await client.query('DELETE FROM inventory_assignments WHERE location_id = ANY($1)', [
          locationIds,
        ]);
      }
      if (bedIds && bedIds.length > 0) {
        await client.query('DELETE FROM inventory_assignments WHERE bed_id = ANY($1)', [bedIds]);
      }
    } else {
      await client.query('DELETE FROM inventory_assignments WHERE id = $1', [id]);
    }
  }

  private async undoDeleteInventoryAssignment(log: UndoLog, client: PoolClient): Promise<void> {
    const id = log.entityId;
    const { catalog_id, location_id, bed_id, quantity, notes } = log.undoData;
    await client.query(
      `INSERT INTO inventory_assignments (id, catalog_id, location_id, bed_id, quantity, notes)
       VALUES ($1, $2, $3, $4, $5, $6)`,
      [id, catalog_id, location_id, bed_id, quantity, notes],
    );
  }

  private async undoUpdateInventoryAssignment(log: UndoLog, client: PoolClient): Promise<void> {
    const id = log.entityId;
    const { quantity, notes } = log.undoData;
    await client.query(
      'UPDATE inventory_assignments SET quantity = $1, notes = $2, updated_at = NOW() WHERE id = $3',
      [quantity, notes, id],
    );
  }

  private async undoApplyInventoryTemplate(log: UndoLog, client: PoolClient): Promise<void> {
    const { createdIds, deletedAssignments } = log.undoData;

    // 1. Remove newly created assignments
    if (createdIds && createdIds.length > 0) {
      await client.query('DELETE FROM inventory_assignments WHERE id = ANY($1)', [createdIds]);
    }

    // 2. Restore deleted assignments
    if (deletedAssignments && deletedAssignments.length > 0) {
      const values: any[] = [];
      const rows: string[] = [];
      let pIdx = 1;

      for (const a of deletedAssignments) {
        rows.push(
          `($${pIdx++}, $${pIdx++}, $${pIdx++}, $${pIdx++}, $${pIdx++}, $${pIdx++}, $${pIdx++}, $${pIdx++})`,
        );
        values.push(
          a.id,
          a.catalog_id,
          a.location_id || null,
          a.bed_id || null,
          a.quantity,
          a.notes || null,
          a.created_at,
          a.updated_at,
        );
      }

      await client.query(
        `INSERT INTO inventory_assignments (id, catalog_id, location_id, bed_id, quantity, notes, created_at, updated_at)
         VALUES ${rows.join(', ')}`,
        values,
      );
    }
  }

  // ===========================================================================
  // Access Card Handlers
  // ===========================================================================

  private async undoCreateCardBatch(log: UndoLog, client: PoolClient): Promise<void> {
    const batchId = parseInt(log.entityId, 10);
    // Deleting a batch also deletes its cards due to ON DELETE CASCADE
    await client.query('DELETE FROM card_batches WHERE id = $1', [batchId]);
  }

  private async undoIssueCard(log: UndoLog, undoUserId: string, client: PoolClient): Promise<void> {
    const cardId = parseInt(log.entityId, 10);
    const { studentId, bookingId } = log.undoData;

    // 1. Revert card to available
    await client.query(
      `UPDATE access_cards 
       SET status = 'available', 
           current_holder_id = NULL, 
           current_booking_id = NULL, 
           issued_at = NULL,
           issued_by = NULL,
           updated_at = NOW()
       WHERE id = $1`,
      [cardId],
    );

    // 2. Add history log for reversal
    await client.query(
      `INSERT INTO access_card_logs (card_id, student_id, booking_id, action_type, performed_by, notes)
       VALUES ($1, $2, $3, 'reversed', $4, $5)`,
      [cardId, studentId, bookingId, undoUserId, 'Undo: Card issuance reversed'],
    );
  }

  private async undoReturnCard(
    log: UndoLog,
    undoUserId: string,
    client: PoolClient,
  ): Promise<void> {
    const cardId = parseInt(log.entityId, 10);
    const { previousStatus, previousHolderId, previousBookingId } = log.undoData;

    // 1. Restore previous issued state
    await client.query(
      `UPDATE access_cards 
       SET status = $1, 
           current_holder_id = $2, 
           current_booking_id = $3, 
           returned_at = NULL,
           updated_at = NOW()
       WHERE id = $4`,
      [previousStatus, previousHolderId, previousBookingId, cardId],
    );

    // 2. Add history log for reversal
    await client.query(
      `INSERT INTO access_card_logs (card_id, student_id, booking_id, action_type, performed_by, notes)
       VALUES ($1, $2, $3, 'returned', $4, $5)`,
      [cardId, previousHolderId, previousBookingId, undoUserId, 'Undo: Card return reversed'],
    );
  }

  private async undoMarkCardQuarantined(
    log: UndoLog,
    undoUserId: string,
    client: PoolClient,
  ): Promise<void> {
    const cardId = parseInt(log.entityId, 10);
    const { previousStatus, previousHolderId, previousBookingId } = log.undoData;

    await client.query(
      `UPDATE access_cards
       SET status = $1,
           current_holder_id = $2,
           current_booking_id = $3,
           updated_at = NOW()
       WHERE id = $4`,
      [previousStatus, previousHolderId ?? null, previousBookingId ?? null, cardId],
    );

    await client.query(
      `INSERT INTO access_card_logs (card_id, student_id, booking_id, action_type, performed_by, notes)
       VALUES ($1, $2, $3, 'reversed', $4, $5)`,
      [
        cardId,
        previousHolderId ?? null,
        previousBookingId ?? null,
        undoUserId,
        'Undo: Card quarantine reversed',
      ],
    );
  }

  private async undoReinstateCard(
    log: UndoLog,
    undoUserId: string,
    client: PoolClient,
  ): Promise<void> {
    const cardId = parseInt(log.entityId, 10);
    const { previousStatus } = log.undoData;

    await client.query(
      `UPDATE access_cards
       SET status = $1,
           current_holder_id = NULL,
           current_booking_id = NULL,
           updated_at = NOW()
       WHERE id = $2`,
      [previousStatus, cardId],
    );

    await client.query(
      `INSERT INTO access_card_logs (card_id, action_type, performed_by, notes)
       VALUES ($1, 'reversed', $2, $3)`,
      [cardId, undoUserId, 'Undo: Card reinstatement reversed'],
    );
  }

  // ===========================================================================
  // Damage Handlers
  // ===========================================================================

  private async undoCreateDamageReport(log: UndoLog, client: PoolClient): Promise<void> {
    const reportId = log.entityId;
    // Deleting a report also deletes its liabilities due to ON DELETE CASCADE
    await client.query('DELETE FROM damage_reports WHERE id = $1', [reportId]);
  }

  private async undoApproveDamageReport(log: UndoLog, client: PoolClient): Promise<void> {
    const reportId = log.entityId;
    const { previousStatus } = log.undoData;

    // 1. Revert report status
    await client.query(
      'UPDATE damage_reports SET status = $1, reviewed_by = NULL, reviewed_at = NULL WHERE id = $2',
      [previousStatus, reportId],
    );

    // 2. Delete the created liabilities
    await client.query('DELETE FROM damage_liabilities WHERE damage_report_id = $1', [reportId]);
  }

  private async undoRejectDamageReport(log: UndoLog, client: PoolClient): Promise<void> {
    const reportId = log.entityId;
    const { previousStatus } = log.undoData;

    await client.query(
      'UPDATE damage_reports SET status = $1, reviewed_by = NULL, reviewed_at = NULL WHERE id = $2',
      [previousStatus, reportId],
    );
  }

  // ===========================================================================
  // Bulk Import Handlers
  // ===========================================================================

  // ===========================================================================
  // Pre-Reservation Handlers
  // ===========================================================================

  private async undoAssignPreReservation(log: UndoLog, client: PoolClient): Promise<void> {
    const { bookingId } = log.undoData;
    const preReservationId = log.entityId;

    if (bookingId) {
      await client.query('DELETE FROM bookings WHERE id = $1', [bookingId]);
    }
    await client.query(
      `UPDATE pre_reservations SET status = 'pending', resolved_by = NULL, resolved_at = NULL,
       booking_id = NULL, updated_at = NOW() WHERE id = $1`,
      [preReservationId],
    );
  }

  private async undoRejectPreReservation(log: UndoLog, client: PoolClient): Promise<void> {
    const preReservationId = log.entityId;
    await client.query(
      `UPDATE pre_reservations SET status = 'pending', resolved_by = NULL, resolved_at = NULL,
       rejection_reason = NULL, updated_at = NOW() WHERE id = $1`,
      [preReservationId],
    );
  }

  // ===========================================================================
  // Room Change Handlers
  // ===========================================================================

  private async undoResolveRoomChange(log: UndoLog, client: PoolClient): Promise<void> {
    const { bookingId, previousBedId, bedWasMoved } = log.undoData;
    const requestId = log.entityId;

    if (bedWasMoved && bookingId && previousBedId) {
      await client.query(
        `UPDATE bookings SET bed_id = $1, room_changes_count = GREATEST(room_changes_count - 1, 0),
         updated_at = NOW() WHERE id = $2`,
        [previousBedId, bookingId],
      );
    }

    await client.query(
      `UPDATE room_change_requests SET status = 'pending', resolved_by = NULL, resolved_at = NULL,
       rejection_reason = NULL, updated_at = NOW() WHERE id = $1`,
      [requestId],
    );
  }

  private async undoApproveRoomChangePayment(log: UndoLog, client: PoolClient): Promise<void> {
    const { bookingId, previousBedId, bedWasMoved } = log.undoData;
    const requestId = log.entityId;

    if (bedWasMoved && bookingId && previousBedId) {
      await client.query(
        `UPDATE bookings SET bed_id = $1, room_changes_count = GREATEST(room_changes_count - 1, 0),
         updated_at = NOW() WHERE id = $2`,
        [previousBedId, bookingId],
      );
    }

    await client.query(
      `UPDATE room_change_requests SET status = 'pending_payment', is_accounting_approved = FALSE,
       accounting_approved_by = NULL, accounting_approved_at = NULL, rejection_reason = NULL,
       updated_at = NOW() WHERE id = $1`,
      [requestId],
    );
  }

  private async undoStaffMoveBed(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousBedId } = log.undoData;
    const bookingId = log.entityId;

    await client.query(`UPDATE bookings SET bed_id = $1, updated_at = NOW() WHERE id = $2`, [
      previousBedId,
      bookingId,
    ]);
  }

  // ===========================================================================
  // Dorm Certificate Handlers
  // ===========================================================================

  private async undoApproveDormCert(log: UndoLog, client: PoolClient): Promise<void> {
    await client.query(
      `UPDATE dorm_certificate_requests
       SET status = 'pending', reviewed_by = NULL, reviewed_at = NULL,
           certificate_storage_key = NULL, certificate_filename = NULL, updated_at = NOW()
       WHERE id = $1`,
      [log.entityId],
    );
  }

  private async undoRejectDormCert(log: UndoLog, client: PoolClient): Promise<void> {
    await client.query(
      `UPDATE dorm_certificate_requests
       SET status = 'pending', reviewed_by = NULL, reviewed_at = NULL,
           rejection_reason = NULL, updated_at = NOW()
       WHERE id = $1`,
      [log.entityId],
    );
  }

  // ===========================================================================
  // Announcement Handlers
  // ===========================================================================

  private async undoCreateAnnouncement(log: UndoLog, client: PoolClient): Promise<void> {
    await client.query(`DELETE FROM announcements WHERE id = $1`, [log.entityId]);
  }

  private async undoUpdateAnnouncement(log: UndoLog, client: PoolClient): Promise<void> {
    const { title, body, pinned, expiresAt } = log.undoData;
    await client.query(
      `UPDATE announcements SET title = $1, body = $2, pinned = $3, expires_at = $4,
       updated_at = NOW() WHERE id = $5`,
      [title, body, pinned, expiresAt ?? null, log.entityId],
    );
  }

  private async undoDeleteAnnouncement(log: UndoLog, client: PoolClient): Promise<void> {
    const { title, body, pinned, isPublished, expiresAt, createdBy } = log.undoData;
    await client.query(
      `INSERT INTO announcements (id, title, body, pinned, is_published, expires_at, created_by)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       ON CONFLICT (id) DO NOTHING`,
      [log.entityId, title, body, pinned, isPublished, expiresAt ?? null, createdBy],
    );
  }

  private async undoPublishAnnouncement(log: UndoLog, client: PoolClient): Promise<void> {
    await client.query(
      `UPDATE announcements SET is_published = FALSE, updated_at = NOW() WHERE id = $1`,
      [log.entityId],
    );
  }

  private async undoUnpublishAnnouncement(log: UndoLog, client: PoolClient): Promise<void> {
    await client.query(
      `UPDATE announcements SET is_published = TRUE, updated_at = NOW() WHERE id = $1`,
      [log.entityId],
    );
  }

  // ===========================================================================
  // Room Type Handlers
  // ===========================================================================

  private async undoCreateRoomType(log: UndoLog, client: PoolClient): Promise<void> {
    await client.query(`DELETE FROM room_types WHERE id = $1`, [log.entityId]);
  }

  private async undoUpdateRoomType(log: UndoLog, client: PoolClient): Promise<void> {
    const { name, nameTr, description, descriptionTr, capacity, amenities } = log.undoData;
    await client.query(
      `UPDATE room_types SET name = $1, name_tr = $2, description = $3, description_tr = $4,
       capacity = $5, amenities = $6, updated_at = NOW() WHERE id = $7`,
      [name, nameTr ?? null, description, descriptionTr ?? null, capacity, amenities, log.entityId],
    );
  }

  private async undoDeleteRoomType(log: UndoLog, client: PoolClient): Promise<void> {
    const { name, nameTr, description, descriptionTr, capacity, amenities } = log.undoData;
    await client.query(
      `INSERT INTO room_types (id, name, name_tr, description, description_tr, capacity, amenities)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       ON CONFLICT (id) DO NOTHING`,
      [
        log.entityId,
        name,
        nameTr ?? null,
        description,
        descriptionTr ?? null,
        capacity,
        JSON.stringify(amenities ?? []),
      ],
    );
  }

  // ===========================================================================
  // Guest Stay Handlers
  // ===========================================================================

  private async undoCreateGuestStay(log: UndoLog, client: PoolClient): Promise<void> {
    await client.query(`DELETE FROM guest_stays WHERE id = $1`, [log.entityId]);
  }

  private async undoCheckInGuestStay(log: UndoLog, client: PoolClient): Promise<void> {
    await client.query(
      `UPDATE guest_stays SET status = 'confirmed', checked_in_at = NULL, updated_at = NOW()
       WHERE id = $1`,
      [log.entityId],
    );
  }

  private async undoCheckOutGuestStay(log: UndoLog, client: PoolClient): Promise<void> {
    await client.query(
      `UPDATE guest_stays SET status = 'active', checked_out_at = NULL, updated_at = NOW()
       WHERE id = $1`,
      [log.entityId],
    );
  }

  private async undoCancelGuestStay(log: UndoLog, client: PoolClient): Promise<void> {
    const { previousStatus } = log.undoData;
    await client.query(`UPDATE guest_stays SET status = $1, updated_at = NOW() WHERE id = $2`, [
      previousStatus,
      log.entityId,
    ]);
  }

  // ===========================================================================
  // Student Application Handlers
  // ===========================================================================

  private async undoApproveApplication(log: UndoLog, client: PoolClient): Promise<void> {
    const { studentId, previousEnrollmentStatus, studentCreatedDuringApproval, insertedCertId } =
      log.undoData;
    const appId = log.entityId;

    // 1. Revert application back to pending
    await client.query(
      `UPDATE student_applications
       SET status = 'pending', reviewed_by = NULL, reviewed_at = NULL, student_id = NULL
       WHERE id = $1`,
      [appId],
    );

    if (studentCreatedDuringApproval) {
      // 2a. Student was created as part of this approval — delete them
      await client.query('DELETE FROM students WHERE id = $1', [studentId]);
    } else {
      // 2b. Student pre-existed — revert enrollment status
      await client.query(
        'UPDATE students SET enrollment_status = $1, updated_at = NOW() WHERE id = $2',
        [previousEnrollmentStatus ?? 'pending', studentId],
      );

      // 3. Delete enrollment cert that was inserted (returning students only)
      if (insertedCertId) {
        await client.query('DELETE FROM student_enrollment_verifications WHERE id = $1', [
          insertedCertId,
        ]);
      }
    }
  }

  private async undoRejectApplication(log: UndoLog, client: PoolClient): Promise<void> {
    await client.query(
      `UPDATE student_applications
       SET status = 'pending', reviewed_by = NULL, reviewed_at = NULL, rejection_reason = NULL
       WHERE id = $1`,
      [log.entityId],
    );
  }

  private async undoBulkImport(log: UndoLog, client: PoolClient): Promise<void> {
    const { batchId, createdStudentIds, createdBookingIds } = log.undoData;
    if (!batchId) throw new BadRequestException('Missing batchId in undo data');

    // 1. SAFETY CHECK: Check if any bookings have been paid for
    if (createdBookingIds && createdBookingIds.length > 0) {
      const paidCheck = await client.query(
        `SELECT id FROM bookings 
         WHERE id = ANY($1) 
           AND payment_status != 'pending'`,
        [createdBookingIds],
      );

      if (paidCheck.rowCount! > 0) {
        throw new BadRequestException(
          'Cannot undo import: Some students have already made payments or have active financial records.',
        );
      }
    }

    // 2. GENDER LOCK CLEANUP: Find locations affected by these bookings
    if (createdBookingIds && createdBookingIds.length > 0) {
      const locationRes = await client.query(
        `SELECT DISTINCT bd.location_id 
         FROM bookings b 
         JOIN beds bd ON b.bed_id = bd.id 
         WHERE b.id = ANY($1)`,
        [createdBookingIds],
      );

      // 3. ATOMIC DELETION: Bookings first
      await client.query('DELETE FROM bookings WHERE id = ANY($1)', [createdBookingIds]);

      // 4. CLEAR GENDER LOCKS if rooms are now empty
      for (const row of locationRes.rows) {
        await this.locationsRepository.clearGenderLockIfEmpty(row.location_id, client);
      }
    }

    // 5. ATOMIC DELETION: Students
    if (createdStudentIds && createdStudentIds.length > 0) {
      await client.query('DELETE FROM students WHERE id = ANY($1)', [createdStudentIds]);
    }

    // 6. Update batch status
    await client.query(
      "UPDATE import_batches SET status = 'failed', notes = 'Import undone by user' WHERE id = $1",
      [batchId],
    );
  }
}
